# Lesson 1. 张量（Tensor）的创建和常用方法

在PyTorch中定义了适用于深度学习的基本数据结构————张量，以及张量的各类计算

张量作为数组的衍生概念，其本身的定义和使用方法和NumPy中的Array非常类似，甚至，在复现一些简单的神经网络算法场景中，我们可以直接使用NumPy中的Array来进行操作。

## 一、张量（Tensor）的基本创建及其类型

### 1.张量（Tensor）函数创建方法

- 张量创建函数`torch.tensor()`
  - 通过列表`torch.tensor([1,2])`
  - 通过元组`torch.tensor((1,2))`
  - 通过数组`torch.tensor(np.array((1,2)))`
  
**Point**： 张量也有detype类型
  

In [18]:
import torch

In [19]:
# 通过列表创建张量

t = torch.tensor([1,2])
t

tensor([1, 2])

In [20]:
# 通过元组创建张量
torch.tensor((1,2))

tensor([1, 2])

In [21]:
# 通过数组创建张量

import numpy  as np

a = np.array((1,2))
a

t1 = torch.tensor(a)
t1

tensor([1, 2], dtype=torch.int32)

**Point**： 张量也有detype类型

In [22]:
type(t)

torch.Tensor

In [23]:
type(t1)

torch.Tensor

### 2.张量的类型

张量和数组类型，都要dtype方法，可返回张量类型。

In [24]:
# 数组类型
a.dtype  # a是array转换过去的

dtype('int32')

In [25]:
t

tensor([1, 2])

In [26]:
t.dtype

torch.int64

In [27]:
t1.dtype

torch.int32

整数型的数组默认创建`int32`（整形）类型，而张量默认创建长整形`int64`
- 但是长整型更加占用内存空间
  


In [31]:
np.array([1.1,2.2]).dtype

dtype('float64')

In [33]:
torch.Tensor(np.array([1.1,2.2])).dtype

torch.float32

In [32]:
torch.Tensor([1.1,2.2]).dtype

torch.float32

  相对的，创建浮点型数组时，张量默认得是单精度浮点型float32，而Array则是默认双精度浮点型float64
    
除了数值型张量，常用的张量类型类型还有布尔型张量，也是构成张量的各元素都是布尔类型的张量


In [36]:
t2 = torch.Tensor([True,False])
t2.dtype

torch.float32

**<center>PyTorch中Tensor类型</center>**


|数据类型|dtype|      
|:--:|:--:|      
|32bit浮点数|torch.float32或torch.float|      
|64bit浮点数|torch.float64或torch.double|	      
|16bit浮点数|torch.float16或torch.half|	      
|8bit无符号整数|torch.unit8|    
|8bit有符号整数|torch.int8|
|16bit有符号整数|torch.int16或torch.short|
|16bit有符号整数|torch.int16或torch.short|
|32bit有符号整数|torch.int32或torch.int|
|64bit有符号整数|torch.int64或torch.long|
|布尔型|torch.bool|
|复数型|torch.complex64|

In [41]:
# 支持复数类型创建  
torch.tensor((1+2j))  

# j 表示叙述

tensor(1.+2.j)

### 3.张量类型的转化

- 张量类型的隐式转化
  - 是torch自动转换的
  - 尽量保留原有的信息
&emsp;&emsp;和NumPy中array相同，当张量各元素属于不同类型时，系统会自动进行隐式转化。

- 张量类型的转换方法
  - `.float()`
  - `.int()`
  - `.short() `

In [42]:
# 浮点型和整数型的隐式转化
torch.tensor([1.1,2]) 

# 默认将整数型转换为浮点型

tensor([1.1000, 2.0000])

In [43]:
torch.tensor([1.1,2]).dtype

torch.float32

In [44]:
# 布尔型和数值型的隐式转化
torch.tensor([False,2.0])  

# 默认把False转换为浮点型了

tensor([0., 2.])

- 张量的转化方法

    当然，我们还可以使用.float()、.int()等方法对张量类型进行转化。

In [45]:
t.float()

tensor([1., 2.])

In [46]:
# 转化为双精度浮点型
t.double

<function Tensor.double>

In [47]:
t.dtype

torch.int64

In [48]:
# 转为为16位证书
t.short

<function Tensor.short>

**Point:**      
- 当在torch函数中使用dtype参数时候，需要输入torch.float表示精度；
- 在使用方法进行类型转化时，方法名称则是double。（虽然torch.float和double都表示双精度浮点型。）

## 二、张量的维度与形变

&emsp;&emsp;张量作为一组数的结构化表示，也同样拥有维度的概念。简答理解，向量就是一维的数组，而矩阵则是二维的数组，以此类推，在张量中，我们还可以定义更高维度的数组。当然，张量的高维数组和NumPy中高维Array概念类似。

### 1.创建高维张量

&emsp;&emsp;包含“简单”元素的序列可创建一维数组

- 用简单序列创建一维数组`torch.tensor([1,2])`
- 用“序列”的“序列”创建二维数组`torch.tensor([[1,2],[3,4]])`
- `ndim`属性查看张量的维度
- `shape `查看形状 和`size()` 函数相同
- `len()`  返回拥有几个（N-1）维元素
- `.numel()`返回总共拥有几个数

In [51]:
t1 = torch.tensor([1,2])
t1

tensor([1, 2])

In [52]:
# ndim属性查看张量的维度
t1.ndim

1

In [53]:
# shape 查看形状
t1.shape

torch.Size([2])

In [54]:
# 和size() 函数相同
t1.size()

torch.Size([2])

> 和NumPy不同,Pytorch中返回的结果和shape属性返回的一致 

In [55]:
len([1,2,3])

3

In [56]:
# 返回拥有几个（N-1）维元素
len(t1)

2

In [59]:
# 返回总共拥有几个数
t1.numel()

2

> **注：**一维张量len和numel返回结果相同，但更高维度张量则不然

- 用“序列”的“序列”创建二维数组

&emsp;&emsp;以此类推，我们还可以用形状相同的序列组成一个新的序列，进而将其转化为二维张量。

In [60]:
# 用list的list创建二维数组
t2 = torch.tensor([[1,2],[3,4]])
t2

tensor([[1, 2],
        [3, 4]])

In [61]:
t2.ndim

2

In [63]:
t2.numel()

4

**理解**：此处len函数返回结果代表t2由两个1维张量构成

- “零”维张量

&emsp;&emsp;在PyTorch中，还有一类特殊的张量，被称为零维张量。该类型张量只包含一个元素，但又不是单独一个数。

In [64]:
t0 = torch.tensor([1])
t0

tensor([1])

In [65]:
# 零维张量(标量 没有方向的数组)
t = torch.tensor(1)
t

tensor(1)

In [66]:
t0.ndim

1

In [67]:
t.ndim

0

In [69]:
t0.shape

torch.Size([1])

In [68]:
t.shape

torch.Size([])

**理解零维张量:**          
&emsp;&emsp;目前，我们可将零维张量视为拥有张量属性的单独一个数。（例如，张量可以存在GPU上，但Python原生的数值型对象不行，但零维张量可以，尽管是零维。）从学术名称来说，Python中单独一个数是scalars（标量），而零维的张量则是tensor。

- 高维张量

&emsp;&emsp;一般来说，三维及三维以上的张量，我们就将其称为高维张量。当然，在高维张量中，最常见的还是三维张量。我们可以将其理解为二维数组或者矩阵的集合。

In [70]:
a1 = np.array([[1, 2, 2], [3, 4, 4]])
a1

array([[1, 2, 2],
       [3, 4, 4]])

In [71]:
a2 = np.array([[5, 6, 6], [7, 8, 8]])
a2

array([[5, 6, 6],
       [7, 8, 8]])

In [73]:
# 将两个形状相同的二维数组创建一个三维的张量
t3 = torch.tensor([a1,a2])
t3

tensor([[[1, 2, 2],
         [3, 4, 4]],

        [[5, 6, 6],
         [7, 8, 8]]], dtype=torch.int32)

In [74]:
t3.ndim

3

In [75]:
t3.shape  # 包含两个，两行三列的矩阵的张量

torch.Size([2, 2, 3])

In [76]:
len(t3)

2

In [77]:
t3.numel()  # 返回元素的个数

12

当然，N维张量的创建方法，我们可以先创建M个N-1维的数组，然后将其拼成一个N维的张量。关于更高维度的张量，我们将在后续遇到时再进行讲解。在张量的学习过程中，三维张量就已经足够。

### 2.张量的形变

&emsp;&emsp;张量作为数字的结构化集合，其结构也是可以根据实际需求灵活调整的。

- `.flatten()` 将任意维度张量转化为一维张量
- `reshape()`任意变形

#### 2.1 flatten拉平：将任意维度张量转化为一维张量

In [78]:
t2.flatten()

tensor([1, 2, 3, 4])

In [79]:
t3.flatten()

tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8], dtype=torch.int32)

> **注**：如果将零维张量使用`flatten`,会转换为1维张量

### 2.2 reshape方法：任意变形

In [81]:
t1

tensor([1, 2])

In [82]:
# 转换为2行一列的张量
t1.reshape(2,1)

tensor([[1],
        [2]])

In [85]:
# reshape 以后改变了张量的维度
t1.ndim
t1.reshape(2,1).ndim

2

In [86]:
t1.reshape(2,1).shape

torch.Size([2, 1])

In [80]:
t1.reshape(2,1)  

# t1.reshaoe(2,)  就等于rshape(2)

tensor([[1],
        [2]])

**注意，reshape过程中维度的变化**：reshape转化后的维度由该方法输入的参数“个数”决定

- 转化后生成一维张量

In [87]:
t1.reshape(2)

tensor([1, 2])

In [88]:
t1.reshape(2).ndim

1

- 转化为二维张量

In [90]:
t1

tensor([1, 2])

In [89]:
t1.reshape(1, 2)        # 生成包含一个两个元素的二维张量

tensor([[1, 2]])

In [91]:
t1.reshape(1,2).ndim

2

- 转化为三维张量

In [92]:
t1.reshape(1,1,2)  # 1个矩阵  一行2列的矩阵

tensor([[[1, 2]]])

In [93]:
t1.reshape(1,2,1)  # 三维张量  包含一个矩阵 2行一列的矩阵

tensor([[[1],
         [2]]])

In [94]:
t1.reshape(1,2,1).ndim

3

## 三、特殊张量的创建方法

&emsp;&emsp;在很多数值科学计算的过程中，都会创建一些特殊取值的张量，用于模拟特殊取值的矩阵，如全0矩阵、对角矩阵等。因此，PyTorch中也存在很多创建特殊张量的函数。

### 1.特殊取值的张量创建方法

- 全0张量`.zeros([2,3])`   
- 全1张量`.ones()`
- 单位矩阵`eye(n)`
- 对角矩阵`diag(tensor类型)`
- `rand()`: 服从0-1均匀分布的张量
- `randn()`: 服从标准正态分布的张量
- `normal()`：服从指定正态分布的张量
- `randint()`: 整数随机采样的结果
- `arange/linspace`: 生成数列
-  `empty`：生成未初始化的指定形状矩阵
-  `full`：根据指定形状，填充指定数值

In [95]:
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

- 全1张量

In [96]:
torch.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

- 单位矩阵

In [97]:
torch.eye(5)  # 5行5列

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

- 对角矩阵
  
  在Pytorch中，利用一维张量去创建对角矩阵

In [98]:
t1

tensor([1, 2])

In [99]:
torch.diag(t1)

tensor([[1, 0],
        [0, 2]])

In [101]:
# 不能使用list直接创建  必需是tensor
torch.diag([1,2])

TypeError: diag(): argument 'input' (position 1) must be Tensor, not list

- rand: 服从0-1均匀分布的张量

In [102]:
torch.rand(2,3)

tensor([[0.6768, 0.0966, 0.8519],
        [0.1986, 0.8930, 0.0462]])

- randn: 服从标准正态分布的张量

In [103]:
torch.randn(2,3)

tensor([[ 0.8565, -1.1723,  0.5805],
        [ 0.6936, -1.5381,  1.1025]])

- normal：服从指定正态分布的张量

In [104]:
torch.normal(2,3,size=(2,3))   # 服从N(2,3) 形状为2行3列的张量

tensor([[-2.7755, -0.0536, -3.3823],
        [-1.6319,  7.3155,  3.2078]])

- randint: 整数随机采样的结果

In [105]:
torch.randint(1,10,[2,4])  #  从1-10 之间随机采样

tensor([[7, 9, 1, 6],
        [6, 9, 9, 6]])

- arange/linspace: 生成数列

In [106]:
torch.arange(5)   #  和range相同

tensor([0, 1, 2, 3, 4])

In [ ]:
torch.arange(1,5,0.5)  # 从1-5（左闭右开），每隔0.5取一个数

In [107]:
torch.linspace(1,5,3)  # 从1-5 等距的取3个数

tensor([1., 3., 5.])

- empty：生成未初始化的指定形状矩阵

In [109]:
torch.empty(2,3)  #  形状取定了，数值没有取定

tensor([[0., 0., 0.],
        [0., 0., 0.]])

- full：根据指定形状，填充指定数值

In [110]:
torch.full([2,4],2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])

### 2.创建指定形状的数组

&emsp;&emsp;当然，我们还能根据指定对象的形状进行数值填充，只需要在上述函数后面加上`_like`即可。

In [111]:
t1

tensor([1, 2])

In [112]:
t2

tensor([[1, 2],
        [3, 4]])

In [ ]:
torch.full_like(t1,2) # 根据t1的形状，填充2

In [113]:
torch.randint_like(t2, 1, 10)

tensor([[5, 2],
        [7, 5]])

In [114]:
torch.zeros_like(t1) 


tensor([0, 0])

**Point:**      
- 更多`_like`函数，可查阅帮助文档；
- 需要注意一点的是，`_like`类型转化需要注意转化前后数据类型一致的问题；

In [115]:
torch.randn_like(t1)                  

# t1是整数，而转化后将变为浮点数，此时代码将报错

RuntimeError: "normal_kernel_cpu" not implemented for 'Long'

In [116]:
t10 = torch.tensor([1.1, 2.2])        
# 重新生成一个新的浮点型张量

t10

tensor([1.1000, 2.2000])

## 四、张量（Tensor）和其他相关类型之间的转化方法

&emsp;&emsp;张量、数组和列表是较为相似的三种类型对象，在实际操作过程中，经常会涉及三种对象的相互转化。在此前张量的创建过程中，我们看到torch.tensor函数可以直接将数组或者列表转化为张量，而我们也可以将张量转化为数组或者列表。另外，前文介绍了0维张量的概念，此处也将进一步给出零维张量和数值对象的转化方法。

- `.numpy`方法：张量转化为数组
- `.tolist`方法：张量转化为列表 or list()
- `.item()`方法：转化为数值
- 

- .numpy方法：张量转化为数组

In [117]:
t1

tensor([1, 2])

In [119]:
t1.numpy()

array([1, 2], dtype=int64)

In [120]:
# 当然，也可以通过np.array函数直接转化为array
np.array(t1)

array([1, 2], dtype=int64)

- .tolist方法：张量转化为列表

In [122]:
t1.tolist()

[1, 2]

- list函数：张量转化为列表

In [123]:
list(t1)

# 由0维张量构成1维张量

[tensor(1), tensor(2)]

> 需要注意的是，此时转化的列表是由一个个零维张量构成的列表，而非张量的数值组成的列表。

- .item()方法：转化为数值

在很多情况下，我们需要将最终计算的结果张量转化为单独的数值进行输出，此时需要使用.item方法来执行

In [124]:
n = torch.tensor(1)
n

tensor(1)

In [125]:
n.item()

1

## 五、张量的深拷贝

&emsp;&emsp;Python中其他对象类型一样，等号赋值操作实际上是浅拷贝，需要进行深拷贝，则需要使用clone方法

- `.clone()`

In [128]:
t1 = torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
t11 = t1             # t11是t1的浅拷贝       
t11

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
t1[1] = 10  # 修改t1的第二位置
t1

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [132]:
t11  # 修改原来的对象，新的对象也同步修改

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

此处t1和t11二者指向相同的对象。而要使得t11不随t1对象改变而改变，则需要对t11进行深拷贝，从而使得t11单独拥有一份对象。

In [133]:
t11 = t1.clone()

In [134]:
t1[0] = 100
t1

tensor([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [135]:
t11

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])